# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='num',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
