# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180512_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
