# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180514_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.PositiveIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
