# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180517_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='group',
        ),
    ]
