# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180514_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num',
        ),
    ]
