# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num',
        ),
    ]
