# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_report_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 17, 21, 53, 39, 282721, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
