# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.PositiveIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
