# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_report_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
