# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180514_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
    ]
