# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180514_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
